services:
  - type: web
    name: transportmanagement
    env: java
    branch: GKCT_104
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/transportation_app_backend-0.0.1-SNAPSHOT.jar
    runtime: java17
    region: singapore
    plan: free
